# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.companies import Companies  # noqa: F401,E501
from swagger_server.models.orders import Orders  # noqa: F401,E501
from swagger_server.models.product_api_response import ProductApiResponse  # noqa: F401,E501
from swagger_server import util


class ContractorApiResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, contractor_id: str=None, username: str=None, emailid: str=None, phone_number: int=None, address: str=None, company: Companies=None, product: List[ProductApiResponse]=None, order: List[Orders]=None):  # noqa: E501
        """ContractorApiResponse - a model defined in Swagger

        :param contractor_id: The contractor_id of this ContractorApiResponse.  # noqa: E501
        :type contractor_id: str
        :param username: The username of this ContractorApiResponse.  # noqa: E501
        :type username: str
        :param emailid: The emailid of this ContractorApiResponse.  # noqa: E501
        :type emailid: str
        :param phone_number: The phone_number of this ContractorApiResponse.  # noqa: E501
        :type phone_number: int
        :param address: The address of this ContractorApiResponse.  # noqa: E501
        :type address: str
        :param company: The company of this ContractorApiResponse.  # noqa: E501
        :type company: Companies
        :param product: The product of this ContractorApiResponse.  # noqa: E501
        :type product: List[ProductApiResponse]
        :param order: The order of this ContractorApiResponse.  # noqa: E501
        :type order: List[Orders]
        """
        self.swagger_types = {
            'contractor_id': str,
            'username': str,
            'emailid': str,
            'phone_number': int,
            'address': str,
            'company': Companies,
            'product': List[ProductApiResponse],
            'order': List[Orders]
        }

        self.attribute_map = {
            'contractor_id': 'contractor_id',
            'username': 'username',
            'emailid': 'emailid',
            'phone_number': 'phone_number',
            'address': 'address',
            'company': 'company',
            'product': 'product',
            'order': 'order'
        }
        self._contractor_id = contractor_id
        self._username = username
        self._emailid = emailid
        self._phone_number = phone_number
        self._address = address
        self._company = company
        self._product = product
        self._order = order

    @classmethod
    def from_dict(cls, dikt) -> 'ContractorApiResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ContractorApiResponse of this ContractorApiResponse.  # noqa: E501
        :rtype: ContractorApiResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def contractor_id(self) -> str:
        """Gets the contractor_id of this ContractorApiResponse.

        contractor id  # noqa: E501

        :return: The contractor_id of this ContractorApiResponse.
        :rtype: str
        """
        return self._contractor_id

    @contractor_id.setter
    def contractor_id(self, contractor_id: str):
        """Sets the contractor_id of this ContractorApiResponse.

        contractor id  # noqa: E501

        :param contractor_id: The contractor_id of this ContractorApiResponse.
        :type contractor_id: str
        """

        self._contractor_id = contractor_id

    @property
    def username(self) -> str:
        """Gets the username of this ContractorApiResponse.


        :return: The username of this ContractorApiResponse.
        :rtype: str
        """
        return self._username

    @username.setter
    def username(self, username: str):
        """Sets the username of this ContractorApiResponse.


        :param username: The username of this ContractorApiResponse.
        :type username: str
        """

        self._username = username

    @property
    def emailid(self) -> str:
        """Gets the emailid of this ContractorApiResponse.


        :return: The emailid of this ContractorApiResponse.
        :rtype: str
        """
        return self._emailid

    @emailid.setter
    def emailid(self, emailid: str):
        """Sets the emailid of this ContractorApiResponse.


        :param emailid: The emailid of this ContractorApiResponse.
        :type emailid: str
        """

        self._emailid = emailid

    @property
    def phone_number(self) -> int:
        """Gets the phone_number of this ContractorApiResponse.


        :return: The phone_number of this ContractorApiResponse.
        :rtype: int
        """
        return self._phone_number

    @phone_number.setter
    def phone_number(self, phone_number: int):
        """Sets the phone_number of this ContractorApiResponse.


        :param phone_number: The phone_number of this ContractorApiResponse.
        :type phone_number: int
        """

        self._phone_number = phone_number

    @property
    def address(self) -> str:
        """Gets the address of this ContractorApiResponse.


        :return: The address of this ContractorApiResponse.
        :rtype: str
        """
        return self._address

    @address.setter
    def address(self, address: str):
        """Sets the address of this ContractorApiResponse.


        :param address: The address of this ContractorApiResponse.
        :type address: str
        """

        self._address = address

    @property
    def company(self) -> Companies:
        """Gets the company of this ContractorApiResponse.


        :return: The company of this ContractorApiResponse.
        :rtype: Companies
        """
        return self._company

    @company.setter
    def company(self, company: Companies):
        """Sets the company of this ContractorApiResponse.


        :param company: The company of this ContractorApiResponse.
        :type company: Companies
        """

        self._company = company

    @property
    def product(self) -> List[ProductApiResponse]:
        """Gets the product of this ContractorApiResponse.


        :return: The product of this ContractorApiResponse.
        :rtype: List[ProductApiResponse]
        """
        return self._product

    @product.setter
    def product(self, product: List[ProductApiResponse]):
        """Sets the product of this ContractorApiResponse.


        :param product: The product of this ContractorApiResponse.
        :type product: List[ProductApiResponse]
        """

        self._product = product

    @property
    def order(self) -> List[Orders]:
        """Gets the order of this ContractorApiResponse.


        :return: The order of this ContractorApiResponse.
        :rtype: List[Orders]
        """
        return self._order

    @order.setter
    def order(self, order: List[Orders]):
        """Sets the order of this ContractorApiResponse.


        :param order: The order of this ContractorApiResponse.
        :type order: List[Orders]
        """

        self._order = order
