# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.login_response_info import LoginResponseInfo  # noqa: F401,E501
from swagger_server import util


class LoginResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, token: str=None, info: LoginResponseInfo=None):  # noqa: E501
        """LoginResponse - a model defined in Swagger

        :param token: The token of this LoginResponse.  # noqa: E501
        :type token: str
        :param info: The info of this LoginResponse.  # noqa: E501
        :type info: LoginResponseInfo
        """
        self.swagger_types = {
            'token': str,
            'info': LoginResponseInfo
        }

        self.attribute_map = {
            'token': 'token',
            'info': 'info'
        }
        self._token = token
        self._info = info

    @classmethod
    def from_dict(cls, dikt) -> 'LoginResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The LoginResponse of this LoginResponse.  # noqa: E501
        :rtype: LoginResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def token(self) -> str:
        """Gets the token of this LoginResponse.

        access token for login  # noqa: E501

        :return: The token of this LoginResponse.
        :rtype: str
        """
        return self._token

    @token.setter
    def token(self, token: str):
        """Sets the token of this LoginResponse.

        access token for login  # noqa: E501

        :param token: The token of this LoginResponse.
        :type token: str
        """

        self._token = token

    @property
    def info(self) -> LoginResponseInfo:
        """Gets the info of this LoginResponse.


        :return: The info of this LoginResponse.
        :rtype: LoginResponseInfo
        """
        return self._info

    @info.setter
    def info(self, info: LoginResponseInfo):
        """Sets the info of this LoginResponse.


        :param info: The info of this LoginResponse.
        :type info: LoginResponseInfo
        """

        self._info = info
