# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class ProductProjects(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, id: str=None, project_name: str=None, project_address: str=None, project_image_url: str=None):  # noqa: E501
        """ProductProjects - a model defined in Swagger

        :param id: The id of this ProductProjects.  # noqa: E501
        :type id: str
        :param project_name: The project_name of this ProductProjects.  # noqa: E501
        :type project_name: str
        :param project_address: The project_address of this ProductProjects.  # noqa: E501
        :type project_address: str
        :param project_image_url: The project_image_url of this ProductProjects.  # noqa: E501
        :type project_image_url: str
        """
        self.swagger_types = {
            'id': str,
            'project_name': str,
            'project_address': str,
            'project_image_url': str
        }

        self.attribute_map = {
            'id': 'id',
            'project_name': 'project_name',
            'project_address': 'project_address',
            'project_image_url': 'project_image_url'
        }
        self._id = id
        self._project_name = project_name
        self._project_address = project_address
        self._project_image_url = project_image_url

    @classmethod
    def from_dict(cls, dikt) -> 'ProductProjects':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Product_projects of this ProductProjects.  # noqa: E501
        :rtype: ProductProjects
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> str:
        """Gets the id of this ProductProjects.


        :return: The id of this ProductProjects.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id: str):
        """Sets the id of this ProductProjects.


        :param id: The id of this ProductProjects.
        :type id: str
        """

        self._id = id

    @property
    def project_name(self) -> str:
        """Gets the project_name of this ProductProjects.


        :return: The project_name of this ProductProjects.
        :rtype: str
        """
        return self._project_name

    @project_name.setter
    def project_name(self, project_name: str):
        """Sets the project_name of this ProductProjects.


        :param project_name: The project_name of this ProductProjects.
        :type project_name: str
        """

        self._project_name = project_name

    @property
    def project_address(self) -> str:
        """Gets the project_address of this ProductProjects.


        :return: The project_address of this ProductProjects.
        :rtype: str
        """
        return self._project_address

    @project_address.setter
    def project_address(self, project_address: str):
        """Sets the project_address of this ProductProjects.


        :param project_address: The project_address of this ProductProjects.
        :type project_address: str
        """

        self._project_address = project_address

    @property
    def project_image_url(self) -> str:
        """Gets the project_image_url of this ProductProjects.


        :return: The project_image_url of this ProductProjects.
        :rtype: str
        """
        return self._project_image_url

    @project_image_url.setter
    def project_image_url(self, project_image_url: str):
        """Sets the project_image_url of this ProductProjects.


        :param project_image_url: The project_image_url of this ProductProjects.
        :type project_image_url: str
        """

        self._project_image_url = project_image_url
