# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class RegisterResponseInfo(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, cus_uid: str=None, username: str=None):  # noqa: E501
        """RegisterResponseInfo - a model defined in Swagger

        :param cus_uid: The cus_uid of this RegisterResponseInfo.  # noqa: E501
        :type cus_uid: str
        :param username: The username of this RegisterResponseInfo.  # noqa: E501
        :type username: str
        """
        self.swagger_types = {
            'cus_uid': str,
            'username': str
        }

        self.attribute_map = {
            'cus_uid': 'cus_uid',
            'username': 'username'
        }
        self._cus_uid = cus_uid
        self._username = username

    @classmethod
    def from_dict(cls, dikt) -> 'RegisterResponseInfo':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The RegisterResponse_info of this RegisterResponseInfo.  # noqa: E501
        :rtype: RegisterResponseInfo
        """
        return util.deserialize_model(dikt, cls)

    @property
    def cus_uid(self) -> str:
        """Gets the cus_uid of this RegisterResponseInfo.


        :return: The cus_uid of this RegisterResponseInfo.
        :rtype: str
        """
        return self._cus_uid

    @cus_uid.setter
    def cus_uid(self, cus_uid: str):
        """Sets the cus_uid of this RegisterResponseInfo.


        :param cus_uid: The cus_uid of this RegisterResponseInfo.
        :type cus_uid: str
        """

        self._cus_uid = cus_uid

    @property
    def username(self) -> str:
        """Gets the username of this RegisterResponseInfo.


        :return: The username of this RegisterResponseInfo.
        :rtype: str
        """
        return self._username

    @username.setter
    def username(self, username: str):
        """Sets the username of this RegisterResponseInfo.


        :param username: The username of this RegisterResponseInfo.
        :type username: str
        """

        self._username = username
