# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class VerifyEmail(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, token: str=None, user_id: str=None):  # noqa: E501
        """VerifyEmail - a model defined in Swagger

        :param token: The token of this VerifyEmail.  # noqa: E501
        :type token: str
        :param user_id: The user_id of this VerifyEmail.  # noqa: E501
        :type user_id: str
        """
        self.swagger_types = {
            'token': str,
            'user_id': str
        }

        self.attribute_map = {
            'token': 'token',
            'user_id': 'user_id'
        }
        self._token = token
        self._user_id = user_id

    @classmethod
    def from_dict(cls, dikt) -> 'VerifyEmail':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The VerifyEmail of this VerifyEmail.  # noqa: E501
        :rtype: VerifyEmail
        """
        return util.deserialize_model(dikt, cls)

    @property
    def token(self) -> str:
        """Gets the token of this VerifyEmail.


        :return: The token of this VerifyEmail.
        :rtype: str
        """
        return self._token

    @token.setter
    def token(self, token: str):
        """Sets the token of this VerifyEmail.


        :param token: The token of this VerifyEmail.
        :type token: str
        """

        self._token = token

    @property
    def user_id(self) -> str:
        """Gets the user_id of this VerifyEmail.


        :return: The user_id of this VerifyEmail.
        :rtype: str
        """
        return self._user_id

    @user_id.setter
    def user_id(self, user_id: str):
        """Sets the user_id of this VerifyEmail.


        :param user_id: The user_id of this VerifyEmail.
        :type user_id: str
        """

        self._user_id = user_id
